services:
  mariadb:
    image: 'mariadb:lts'
    environment:
      - 'MARIADB_DATABASE=monorepo'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=user'
    ports:
      - '3306:3306'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
