spring:
  config:
    import:
      - application-datasource.yaml
---
spring.config.activate.on-profile: local
spring.jpa:
  open-in-view: false
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      highlight_sql: true

---
spring.config.activate.on-profile: dev
spring.jpa:
  open-in-view: false
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      highlight_sql: false

---
spring.config.activate.on-profile: prod
spring.jpa:
  open-in-view: false
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      show_sql: true
      format_sql: false
      highlight_sql: false
---
